name: gigantic_ticket_wallet
description: "Gigantic ticket wallet app. App for storing tickets provided by gigantic."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  get_it: ^7.7.0
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  package_info_plus: ^7.0.0
  internet_connection_checker_plus: ^2.3.0
  go_router: ^13.2.4
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_slidable: ^3.1.0
  screen_brightness: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  test: ^1.24.9
  patrol: ^3.6.1
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

patrol:
  app_name: gigantic_ticket_wallet
  android:
    package_name: com.gigantic.gigantic_ticket_wallet
  ios:
    bundle_id: com.gigantic.giganticTicketWallet
